from __future__ import annotations

from bot_worker.services.alert_delivery import (
    AlertDeliveryConfig,
    dispatch_pending_alerts,
    format_alert_message,
    format_webhook_payload,
    send_test_alert,
    send_test_alert_to_channel,
)
from bot_worker.services.alerts import (
    record_alert_decisions,
)
from bot_worker.services.digests import (
    build_digest_record,
    digest_display_headline,
    digest_preview,
    digest_time_in_window,
    event_report_time_range,
    format_digest_message,
    format_report_time_range,
    format_report_time_span,
    select_digest_headline,
    select_report_time_range,
    send_digest_record,
)
from bot_worker.services.embeddings import (
    embed_pending_event_clusters,
    embed_pending_news_items,
    validate_embedding_dimensions,
)
from bot_worker.services.events import (
    ClusterBuildStats,
    build_event_clusters,
    compact_archived_events,
    merge_event_clusters,
    recluster_recent_event_clusters,
    split_event_cluster,
    vector_cluster_candidates_for_item,
)
from bot_worker.services.extraction_audit import (
    audit_source_extraction,
)
from bot_worker.services.ingestion import (
    is_rss_item_fresh,
    mark_exact_duplicates,
    normalize_pending_raw_items,
    raw_item_from_parsed,
)
from bot_worker.services.investigation import (
    latest_successful_investigation,
    list_pending_investigations,
    queue_event_investigation_runs,
    queue_investigation,
    queue_investigations_for_events,
    queue_investigations_for_missed_catalysts,
    run_asset_investigation,
    run_event_investigation,
    run_existing_investigation,
    run_investigations_concurrently,
    run_pending_investigations,
)
from bot_worker.services.jobs import (
    record_job_run,
)
from bot_worker.services.llm import (
    classify_news_item_with_llm,
    enrich_event_clusters_with_llm,
    extract_entities_with_llm,
    latest_llm_analysis,
    latest_successful_llm_analysis,
    score_event_with_llm,
    summarize_event_with_llm,
)
from bot_worker.services.market import (
    fetch_market_moves,
    fetch_market_moves_with_stats,
    market_move_score_for_cluster,
    run_missed_catalyst_review,
    store_market_moves,
)
from common.market_symbol_resolver import (
    resolve_watchlist_market_symbol,
    watchlist_market_symbol_requests,
)
from bot_worker.services.pipeline import (
    CORE_JOBS,
    run_pipeline,
)
from bot_worker.services.retention import (
    baseline_reset_preview,
    retention_preview,
    run_baseline_reset,
    run_retention,
)
from bot_worker.services.sources import (
    add_source,
    compute_source_quality,
    effective_source_score,
    fetch_source,
    fetch_source_content,
    get_source,
    import_sources_yaml,
    list_sources,
    purge_source,
    refresh_source_quality_scores,
    seed_configuration_presets,
    seed_starter_sources,
    set_source_enabled,
)
from bot_worker.services.watchlists import (
    add_watchlist_entry,
    news_item_entities,
    news_item_tickers,
    watchlist_entries,
)

__all__ = [
    "AlertDeliveryConfig",
    "CORE_JOBS",
    "ClusterBuildStats",
    "add_source",
    "add_watchlist_entry",
    "audit_source_extraction",
    "baseline_reset_preview",
    "build_digest_record",
    "build_event_clusters",
    "classify_news_item_with_llm",
    "compact_archived_events",
    "compute_source_quality",
    "digest_display_headline",
    "digest_preview",
    "digest_time_in_window",
    "dispatch_pending_alerts",
    "embed_pending_event_clusters",
    "embed_pending_news_items",
    "effective_source_score",
    "enrich_event_clusters_with_llm",
    "event_report_time_range",
    "extract_entities_with_llm",
    "fetch_market_moves",
    "fetch_market_moves_with_stats",
    "fetch_source",
    "fetch_source_content",
    "format_report_time_range",
    "format_report_time_span",
    "format_digest_message",
    "format_alert_message",
    "format_webhook_payload",
    "get_source",
    "import_sources_yaml",
    "is_rss_item_fresh",
    "latest_successful_investigation",
    "latest_llm_analysis",
    "latest_successful_llm_analysis",
    "list_pending_investigations",
    "list_sources",
    "mark_exact_duplicates",
    "market_move_score_for_cluster",
    "merge_event_clusters",
    "news_item_entities",
    "news_item_tickers",
    "normalize_pending_raw_items",
    "purge_source",
    "queue_event_investigation_runs",
    "queue_investigation",
    "queue_investigations_for_events",
    "queue_investigations_for_missed_catalysts",
    "raw_item_from_parsed",
    "record_alert_decisions",
    "record_job_run",
    "resolve_watchlist_market_symbol",
    "recluster_recent_event_clusters",
    "refresh_source_quality_scores",
    "retention_preview",
    "run_baseline_reset",
    "run_asset_investigation",
    "run_event_investigation",
    "run_existing_investigation",
    "run_missed_catalyst_review",
    "run_pending_investigations",
    "run_investigations_concurrently",
    "run_pipeline",
    "run_retention",
    "score_event_with_llm",
    "seed_configuration_presets",
    "seed_starter_sources",
    "select_digest_headline",
    "select_report_time_range",
    "send_test_alert",
    "send_test_alert_to_channel",
    "send_digest_record",
    "set_source_enabled",
    "split_event_cluster",
    "store_market_moves",
    "summarize_event_with_llm",
    "validate_embedding_dimensions",
    "vector_cluster_candidates_for_item",
    "watchlist_entries",
    "watchlist_market_symbol_requests",
]
